# Disable ICMP Redirect Acceptance
net.ipv4.conf.all.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0

# Enable IP Spoofing Protection
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Ignore ICMP Echo Requests (Ping)
# BPFdoor uses Magic ICMP packets. By ignoring standard pings at the kernel level,
# the system appears dead to scanners, but BPFdoor catches the packet BEFORE this rule applies.
net.ipv4.icmp_echo_ignore_all = 1

# Log Spoofed Packets, Source Routed Packets, Redirect Packets
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1
